apiVersion: v1
kind: Pod
metadata:
  name: cmle-basic-test
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: basic-test
      image: python:latest
      command: ["/bin/sh","-c"]
      args: ["wget -NP /usr/bin https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            && chmod 755 /usr/bin/kubectl
            && pip install nose-tap
            && nosetests --with-tap /tests/run.py"]
      volumeMounts:
      - mountPath: /tests
        name: tests
        readOnly: true
      - mountPath: /tools
        name: tools
  volumes:
  - name: tests
    configMap:
      name: cmle-tests
  - name: tools
    emptyDir: {}
  restartPolicy: Never